-   id: flake8
    name: Flake8 (removed)
    description: (removed) use gitlab.com/pycqa/flake8 instead.
    entry: pre-commit-hooks-removed flake8 flake8 https://gitlab.com/pycqa/flake8
    language: python
    always_run: true
    pass_filenames: false
